const QueryTypes = {
    AUTO: "AUTO",

    YOUTUBE_VIDEO: "YOUTUBE_VIDEO",
    YOUTUBE_PLAYLIST: "YOUTUBE_PLAYLIST",

    SPOTIFY_SONG: "SPOTIFY_SONG",
    SPOTIFY_ALBUM: "SPOTIFY_ALBUM",
    SPOTIFY_PLAYLIST: "SPOTIFY_PLAYLIST",

    SOUNDCLOUD_SONG: "SOUNDCLOUD_SONG",
    SOUNDCLOUD_PLAYLIST: "SOUNDCLOUD_PLAYLIST",

    YOUTUBE_SEARCH: "YOUTUBE_SEARCH",
}

const LoadType = {
    TRACK_LOADED: "TRACK_LOADED",
    PLAYLIST_LOADED: "PLAYLIST_LOADED",
    SEARCH_RESULT: "SEARCH_RESULT",
    LOAD_FAILED: "LOAD_FAILED",
    NO_MATCHES: "NO_MATCHES"
}

const State = {
    CONNECTED: "CONNECTED",
    CONNECTING: "CONNECTING",
    DISCONNECTED: "DISCONNECTED",
    DISCONNECTING: "DISCONNECTING",
    DESTROYING: "DESTROYING"
}

const RepeatMode = {
    OFF: "OFF",
    QUEUE: "QUEUE",
    TRACK: "TRACK"
}

module.exports = { QueryTypes, LoadType, State, RepeatMode }